### ISSUE TITLE
Podríamos hacerlo un poco mas general, osea no general total como un ORM

### ISSUE THREAD

**Issue by MasterDjmov** [marcelobettini/dhmovies#1]
const fs = require("node:fs/promises");
const path = require("node:path");

const datasource = {
  filePath: "",

  agregarURL(ruta) {
    this.filePath = ruta;
  },

  async load() {
    const jsonMovies = await fs.readFile(this.filePath, "utf-8");
    const movies = JSON.parse(jsonMovies);
    return movies;
  },

  async save(data) {
    const jsonData = JSON.stringify(data, null, 2); // Incluye una sangría de 2 espacios para legibilidad
    await fs.writeFile(this.filePath, jsonData, "utf-8");
  },
};

module.exports = datasource;

y luego 

const path = require("node:path");
const dataSource = require("../services/datasource.js").agregarURL(path.resolve(__dirname, "../models/movies.json"));

asi podemos usar ese pequeño template como molde para otros archivos, solo cambiando el filePath

como practica esta buena profe.

**Comment by marcelobettini** [comment]
Buenísimo! Toda oportunidad de mejora que le quieras agregar suma. Yo lo tiré bastante simple porque no va a sobrevivir mucho tiempo la persistencia en el sistema de archivos, pero se puede hacer mucho más robusto. De hecho, fijate que ni le puse manejo de errores, cosa que también se podría agregar.
